# Generated by Django 3.2.16 on 2022-11-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BaggageClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=3)),
                ('terminal', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('schedule_time', models.DateTimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_system.airline')),
                ('baggage_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport_system.baggageclaim')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_system.gate')),
            ],
        ),
        migrations.AlterField(
            model_name='airlineemp',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport_system.airline'),
        ),
    ]
