# Generated by Django 3.2.16 on 2022-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0002_auto_20221111_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.CharField(default='A1234', max_length=6, primary_key=True, serialize=False),
        ),
    ]
