# Generated by Django 3.2.16 on 2022-11-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0003_auto_20221115_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport_system.gate'),
        ),
    ]
